import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import img from "../../public/img.png"
import Image from "next/image";
import Link from 'next/link'


export default function Home() {
    return (
        <>
            <Head>
                <title>Fe Assignment</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div className={styles.mainGrid}>
                <div className={styles.tile}>
                    <h2 className={styles.header}>Header</h2>
                    <h3 className={styles.subheader}>subheader</h3>
                    <p className={styles.paragraph}>Sed ut perspiciatis, unde omnis iste natus error sit voluptatem
                        accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore
                        veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam
                        voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni
                        dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem
                        ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi
                        tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima
                        veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex
                        ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit
                        esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas
                        nulla pariatur?</p>
                    <Link href="/posts">
                        <button className={styles.button}>button</button>
                    </Link>
                </div>

                <div className={styles.multipleTile}>
                    <div className={styles.tileWithBackground}>
                        <div className={styles.overlay}></div>
                        <div className={styles.tileWithBackgroundTextWrapper}>
                            <Image
                                width="100"
                                height="80"
                                src={img}
                                alt="logo"></Image>
                        </div>
                    </div>
                    <div className={styles.tileWithBackground}>
                    </div>
                    <div className={styles.tileWithBackground}>
                    </div>
                    <div className={styles.tileWithBackground}>
                        <div className={styles.overlay}></div>
                        <div className={styles.tileWithBackgroundTextWrapper}>
                            <p className={styles.paragraph}>Sed ut perspiciatis, unde omnis iste natus error sit
                                voluptatem
                                accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore
                                veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam
                                voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur
                                magni
                            </p>
                        </div>
                    </div>
                </div>

                <div className={styles.tileWithBackground}>
                    <div className={styles.overlay}></div>
                    <div className={styles.tileWithBackgroundTextWrapper}>
                        <h3 className={styles.header}>Lorem ipsum </h3>
                        <h3 className={styles.header}>Lorem ipsum </h3>
                        <h3 className={styles.header}>Lorem ipsum </h3>
                        <h3 className={styles.header}>Lorem ipsum </h3>
                        <h3 className={styles.header}>Lorem ipsum </h3>
                    </div>
                </div>

                <div className={styles.tile}>
                    <h2 className={styles.header}>Header</h2>
                    <h3 className={styles.subheader}>subheader</h3>
                    <p className={styles.paragraph}>Sed ut perspiciatis, unde omnis iste natus error sit voluptatem
                        accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore
                        veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam
                        voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni
                        dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem
                        ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi
                        tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima
                        veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex
                        ea commodi consequatur? Quis autem vel eum iure reprehenderit, qui in ea voluptate velit
                        esse, quam nihil molestiae consequatur, vel illum, qui dolorem eum fugiat, quo voluptas
                        nulla pariatur?</p>
                    <button className={styles.button}>button</button>
                </div>

            </div>
        </>
    )
}
